<a href="https://colab.research.google.com/github/trprince21/calisthenics_scoring/blob/main/STATS101C_Week0_discussion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import numpy as np

In [42]:
a = np.array([1,2,3], dtype='int32') # vectors R /lists Python

In [43]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]]) # matrices
print(b)
#b[1,]
b[1,2]

[[9. 8. 7.]
 [6. 5. 4.]]


4.0

In [44]:
# Get Dimension
#a.ndim
b.ndim

2

In [45]:
# Get Shape
b.shape

(2, 3)

In [46]:
# Get Type
a.dtype

dtype('int32')

In [47]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]]) # vectors R /lists Python
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [48]:
# Get a specific element [r, c]
a[1, 5]

13

In [49]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [51]:
a[:, 2]

array([ 3, 10])

In [52]:
#a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 13 14]]


In [53]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # 3D matrix
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [54]:
# Get a specific element (work outside in)
b[0,1,1]

4

In [56]:
# replace
b[:,:,1] = [[9,9],[8,3]]
print(b)

[[[1 9]
  [3 9]]

 [[5 8]
  [7 3]]]


In [57]:
# All 0s matrix
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [59]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [60]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [61]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [62]:
np.random.rand(4,2)

array([[0.09335087, 0.31602518],
       [0.02639834, 0.08851198],
       [0.51672682, 0.32901658],
       [0.26460255, 0.53426334]])

In [64]:
np.random.randint(-4,8, size=(3,3))

array([[ 1,  3,  3],
       [-4, -2,  6],
       [-2,  7, -2]])

In [ ]:
np.identity(5)

In [67]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


We want a 5 by 5 matrix with ones on the outer element, 0 on the inner elements and 9 in the center element


In [ ]:
np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])